import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const copyToTestVault = {
    name: "copy-to-test-vault",
    setup(build) {
        build.onEnd(() => {
            if (!prod) {
                const dest = "test-vault/.obsidian/plugins/xournalpp";
                if (!fs.existsSync(dest)) {
                    fs.mkdirSync(dest, { recursive: true });
                }
                fs.copyFileSync("main.js", `${dest}/main.js`);
                fs.copyFileSync("manifest.json", `${dest}/manifest.json`);
                fs.copyFileSync("styles.css", `${dest}/styles.css`);
                fs.writeFileSync(`${dest}/.hotreload`, "");
                console.log("⚡ Copied plugin files to test-vault");
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [copyToTestVault],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
