export const newFilePlaceholders = [
    {
        title: "Interactive",
        placeholders: [
            { pattern: "cursor", example: "", description: "Places the cursor at this position, only allowed once" },
            { pattern: "fname", example: "my_filename", description: "Filename of the currently opened file" },
        ],
    },
    {
        title: "Date & Time",
        placeholders: [
            { pattern: "YY", example: "25", description: "Two-digit year" },
            { pattern: "YYYY", example: "2025", description: "Four-digit year" },
            { pattern: "M", example: "1-12", description: "The month, beginning at 1" },
            { pattern: "MM", example: "01-12", description: "The month, 2-digits" },
            { pattern: "MMM", example: "Jan-Dec", description: "The abbreviated month name" },
            { pattern: "MMMM", example: "January-December", description: "The full month name" },
            { pattern: "D", example: "1-31", description: "The day of the month" },
            { pattern: "DD", example: "01-31", description: "The day of the month, 2-digits" },
            { pattern: "d", example: "0-6", description: "The day of the week, with Sunday as 0" },
            { pattern: "dd", example: "Su-Sa", description: "The min name of the day of the week" },
            { pattern: "ddd", example: "Sun-Sat", description: "The short name of the day of the week" },
            { pattern: "dddd", example: "Sunday-Saturday", description: "The name of the day of the week" },
            { pattern: "H", example: "0-23", description: "The hour" },
            { pattern: "HH", example: "00-23", description: "The hour, 2-digits" },
            { pattern: "h", example: "1-12", description: "The hour, 12-hour clock" },
            { pattern: "hh", example: "01-12", description: "The hour, 12-hour clock, 2-digits" },
            { pattern: "m", example: "0-59", description: "The minute" },
            { pattern: "mm", example: "00-59", description: "The minute, 2-digits" },
            { pattern: "s", example: "0-59", description: "The second" },
            { pattern: "ss", example: "00-59", description: "The second, 2-digits" },
            { pattern: "SSS", example: "000-999", description: "The millisecond, 3-digits" },
            { pattern: "A", example: "AM PM", description: "The ante meridiem and post meridiem uppercase" },
            { pattern: "a", example: "am pm", description: "The ante meridiem and post meridiem lowercase" },
            { pattern: "Q", example: "1-4", description: "Quarter" },
            { pattern: "Do", example: "1st 2nd ... 31st", description: "Day of Month with ordinal" },
            { pattern: "k", example: "1-24", description: "The hour, beginning at 1" },
            { pattern: "kk", example: "01-24", description: "The hour, 2-digits, beginning at 1" },
            { pattern: "X", example: "1360013296", description: "Unix Timestamp in second" },
            { pattern: "x", example: "1360013296123", description: "Unix Timestamp in millisecond" },
            { pattern: "w", example: "1 2 ... 52 53", description: "Week of year" },
            { pattern: "ww", example: "01 02 ... 52 53", description: "Week of year, 2-digits" },
            { pattern: "W", example: "1 2 ... 52 53", description: "ISO Week of year" },
            { pattern: "WW", example: "01 02 ... 52 53", description: "ISO Week of year, 2-digits" },
            {
                pattern: "wo",
                example: "1st 2nd ... 52nd 53rd",
                description: "Week of year with ordinal",
            },
        ],
    },
];
