export const shorthands = [
    {
        title: "Custom",
        shorthands: [
            { shorthand: "cursor", example: "", description: "Places the cursor a this position, only allowed once" },
            { shorthand: "fname", example: "my_filename", description: "Filename of the currently opened file" },
        ],
    },
    {
        title: "Date & Time",
        shorthands: [
            { shorthand: "YY", example: "25", description: "Two-digit year" },
            { shorthand: "YYYY", example: "2025", description: "Four-digit year" },
            { shorthand: "M", example: "1-12", description: "The month, beginning at 1" },
            { shorthand: "MM", example: "01-12", description: "The month, 2-digits" },
            { shorthand: "MMM", example: "Jan-Dec", description: "The abbreviated month name" },
            { shorthand: "MMMM", example: "January-December", description: "The full month name" },
            { shorthand: "D", example: "1-31", description: "The day of the month" },
            { shorthand: "DD", example: "01-31", description: "The day of the month, 2-digits" },
            { shorthand: "d", example: "0-6", description: "The day of the week, with Sunday as 0" },
            { shorthand: "dd", example: "Su-Sa", description: "The min name of the day of the week" },
            { shorthand: "ddd", example: "Sun-Sat", description: "The short name of the day of the week" },
            { shorthand: "dddd", example: "Sunday-Saturday", description: "The name of the day of the week" },
            { shorthand: "H", example: "0-23", description: "The hour" },
            { shorthand: "HH", example: "00-23", description: "The hour, 2-digits" },
            { shorthand: "h", example: "1-12", description: "The hour, 12-hour clock" },
            { shorthand: "hh", example: "01-12", description: "The hour, 12-hour clock, 2-digits" },
            { shorthand: "m", example: "0-59", description: "The minute" },
            { shorthand: "mm", example: "00-59", description: "The minute, 2-digits" },
            { shorthand: "s", example: "0-59", description: "The second" },
            { shorthand: "ss", example: "00-59", description: "The second, 2-digits" },
            { shorthand: "SSS", example: "000-999", description: "The millisecond, 3-digits" },
            { shorthand: "A", example: "AM PM", description: "The ante meridiem and post meridiem uppercase" },
            { shorthand: "a", example: "am pm", description: "The ante meridiem and post meridiem lowercase" },
            { shorthand: "Q", example: "1-4", description: "Quarter" },
            { shorthand: "Do", example: "1st 2nd ... 31st", description: "Day of Month with ordinal" },
            { shorthand: "k", example: "1-24", description: "The hour, beginning at 1" },
            { shorthand: "kk", example: "01-24", description: "The hour, 2-digits, beginning at 1" },
            { shorthand: "X", example: "1360013296", description: "Unix Timestamp in second" },
            { shorthand: "x", example: "1360013296123", description: "Unix Timestamp in millisecond" },
            { shorthand: "w", example: "1 2 ... 52 53", description: "Week of year" },
            { shorthand: "ww", example: "01 02 ... 52 53", description: "Week of year, 2-digits" },
            { shorthand: "W", example: "1 2 ... 52 53", description: "ISO Week of year" },
            { shorthand: "WW", example: "01 02 ... 52 53", description: "ISO Week of year, 2-digits" },
            {
                shorthand: "wo",
                example: "1st 2nd ... 52nd 53rd",
                description: "Week of year with ordinal",
            },
        ],
    },
];
